//
//	ARB_EXT.H
//

#pragma once

class EArbExt
	{
	private:
	public:
		// FRAGMENT SHADERS :
		PFNGLPROGRAMSTRINGARBPROC					glProgramStringARB				 ;
		PFNGLBINDPROGRAMARBPROC						glBindProgramARB				 ;
		PFNGLDELETEPROGRAMSARBPROC					glDeleteProgramsARB              ;
		PFNGLGENPROGRAMSARBPROC						glGenProgramsARB                 ;
		PFNGLPROGRAMENVPARAMETER4DARBPROC			glProgramEnvParameter4dARB       ;
		PFNGLPROGRAMENVPARAMETER4DVARBPROC			glProgramEnvParameter4dvARB      ;
		PFNGLPROGRAMENVPARAMETER4FARBPROC			glProgramEnvParameter4fARB       ;
		PFNGLPROGRAMENVPARAMETER4FVARBPROC			glProgramEnvParameter4fvARB      ;
		PFNGLPROGRAMLOCALPARAMETER4DARBPROC			glProgramLocalParameter4dARB     ;
		PFNGLPROGRAMLOCALPARAMETER4DVARBPROC		glProgramLocalParameter4dvARB    ;
		PFNGLPROGRAMLOCALPARAMETER4FARBPROC			glProgramLocalParameter4fARB     ;
		PFNGLPROGRAMLOCALPARAMETER4FVARBPROC		glProgramLocalParameter4fvARB    ;
		PFNGLGETPROGRAMENVPARAMETERDVARBPROC		glGetProgramEnvParameterdvARB    ;
		PFNGLGETPROGRAMENVPARAMETERFVARBPROC		glGetProgramEnvParameterfvARB    ;
		PFNGLGETPROGRAMLOCALPARAMETERDVARBPROC		glGetProgramLocalParameterdvARB  ;
		PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC		glGetProgramLocalParameterfvARB  ;
		PFNGLGETPROGRAMIVARBPROC					glGetProgramivARB                ;
		PFNGLGETPROGRAMSTRINGARBPROC				glGetProgramStringARB            ;
		PFNGLISPROGRAMARBPROC						glIsProgramARB                   ;

		// VERTEX SHADERS :
		PFNGLVERTEXATTRIB1SARBPROC					glVertexAttrib1sARB           ; 
		PFNGLVERTEXATTRIB1FARBPROC					glVertexAttrib1fARB           ; 
		PFNGLVERTEXATTRIB1DARBPROC					glVertexAttrib1dARB           ; 
		PFNGLVERTEXATTRIB2SARBPROC					glVertexAttrib2sARB           ; 
		PFNGLVERTEXATTRIB2FARBPROC					glVertexAttrib2fARB           ; 
		PFNGLVERTEXATTRIB2DARBPROC					glVertexAttrib2dARB           ; 
		PFNGLVERTEXATTRIB3SARBPROC					glVertexAttrib3sARB           ; 
		PFNGLVERTEXATTRIB3FARBPROC					glVertexAttrib3fARB           ; 
		PFNGLVERTEXATTRIB3DARBPROC					glVertexAttrib3dARB           ; 
		PFNGLVERTEXATTRIB4SARBPROC					glVertexAttrib4sARB           ; 
		PFNGLVERTEXATTRIB4FARBPROC					glVertexAttrib4fARB           ; 
		PFNGLVERTEXATTRIB4DARBPROC					glVertexAttrib4dARB           ; 
		PFNGLVERTEXATTRIB4NUBARBPROC				glVertexAttrib4NubARB         ; 
		PFNGLVERTEXATTRIB1SVARBPROC					glVertexAttrib1svARB          ; 
		PFNGLVERTEXATTRIB1FVARBPROC					glVertexAttrib1fvARB          ; 
		PFNGLVERTEXATTRIB1DVARBPROC					glVertexAttrib1dvARB          ; 
		PFNGLVERTEXATTRIB2SVARBPROC					glVertexAttrib2svARB          ; 
		PFNGLVERTEXATTRIB2FVARBPROC					glVertexAttrib2fvARB          ; 
		PFNGLVERTEXATTRIB2DVARBPROC					glVertexAttrib2dvARB          ; 
		PFNGLVERTEXATTRIB3SVARBPROC					glVertexAttrib3svARB          ; 
		PFNGLVERTEXATTRIB3FVARBPROC					glVertexAttrib3fvARB          ; 
		PFNGLVERTEXATTRIB3DVARBPROC					glVertexAttrib3dvARB          ; 
		PFNGLVERTEXATTRIB4BVARBPROC					glVertexAttrib4bvARB          ; 
		PFNGLVERTEXATTRIB4SVARBPROC					glVertexAttrib4svARB          ; 
		PFNGLVERTEXATTRIB4IVARBPROC					glVertexAttrib4ivARB          ; 
		PFNGLVERTEXATTRIB4UBVARBPROC				glVertexAttrib4ubvARB         ; 
		PFNGLVERTEXATTRIB4USVARBPROC				glVertexAttrib4usvARB         ; 
		PFNGLVERTEXATTRIB4UIVARBPROC				glVertexAttrib4uivARB         ; 
		PFNGLVERTEXATTRIB4FVARBPROC					glVertexAttrib4fvARB          ; 
		PFNGLVERTEXATTRIB4DVARBPROC					glVertexAttrib4dvARB          ; 
		PFNGLVERTEXATTRIB4NBVARBPROC				glVertexAttrib4NbvARB         ; 
		PFNGLVERTEXATTRIB4NSVARBPROC				glVertexAttrib4NsvARB         ; 
		PFNGLVERTEXATTRIB4NIVARBPROC				glVertexAttrib4NivARB         ; 
		PFNGLVERTEXATTRIB4NUBVARBPROC				glVertexAttrib4NubvARB        ; 
		PFNGLVERTEXATTRIB4NUSVARBPROC				glVertexAttrib4NusvARB        ; 	 
		PFNGLVERTEXATTRIB4NUIVARBPROC				glVertexAttrib4NuivARB        ; 	 
		PFNGLVERTEXATTRIBPOINTERARBPROC				glVertexAttribPointerARB      ; 	 
		PFNGLENABLEVERTEXATTRIBARRAYARBPROC			glEnableVertexAttribArrayARB  ; 	 
		PFNGLDISABLEVERTEXATTRIBARRAYARBPROC		glDisableVertexAttribArrayARB ; 	 
		PFNGLGETVERTEXATTRIBDVARBPROC				glGetVertexAttribdvARB        ; 	 
		PFNGLGETVERTEXATTRIBFVARBPROC				glGetVertexAttribfvARB        ; 	 
		PFNGLGETVERTEXATTRIBIVARBPROC				glGetVertexAttribivARB        ; 	 
		PFNGLGETVERTEXATTRIBPOINTERVARBPROC			glGetVertexAttribPointervARB  ; 	 

		// MULTITEXTURE :
		PFNGLACTIVETEXTUREARBPROC					glActiveTextureARB			;
		PFNGLCLIENTACTIVETEXTUREARBPROC				glClientActiveTextureARB	;
		PFNGLMULTITEXCOORD1DARBPROC 				glMultiTexCoord1dARB 		;
		PFNGLMULTITEXCOORD1DVARBPROC				glMultiTexCoord1dvARB		;
		PFNGLMULTITEXCOORD1FARBPROC 				glMultiTexCoord1fARB 		;
		PFNGLMULTITEXCOORD1FVARBPROC				glMultiTexCoord1fvARB		;
		PFNGLMULTITEXCOORD1IARBPROC 				glMultiTexCoord1iARB 		;
		PFNGLMULTITEXCOORD1IVARBPROC				glMultiTexCoord1ivARB		;
		PFNGLMULTITEXCOORD1SARBPROC 				glMultiTexCoord1sARB 		;
		PFNGLMULTITEXCOORD1SVARBPROC				glMultiTexCoord1svARB		;
		PFNGLMULTITEXCOORD2DARBPROC 				glMultiTexCoord2dARB 		;
		PFNGLMULTITEXCOORD2DVARBPROC				glMultiTexCoord2dvARB		;
		PFNGLMULTITEXCOORD2FARBPROC 				glMultiTexCoord2fARB 		;
		PFNGLMULTITEXCOORD2FVARBPROC				glMultiTexCoord2fvARB		;
		PFNGLMULTITEXCOORD2IARBPROC 				glMultiTexCoord2iARB 		;
		PFNGLMULTITEXCOORD2IVARBPROC				glMultiTexCoord2ivARB		;
		PFNGLMULTITEXCOORD2SARBPROC 				glMultiTexCoord2sARB 		;
		PFNGLMULTITEXCOORD2SVARBPROC				glMultiTexCoord2svARB		;
		PFNGLMULTITEXCOORD3DARBPROC 				glMultiTexCoord3dARB 		;
		PFNGLMULTITEXCOORD3DVARBPROC				glMultiTexCoord3dvARB		;
		PFNGLMULTITEXCOORD3FARBPROC 				glMultiTexCoord3fARB 		;
		PFNGLMULTITEXCOORD3FVARBPROC				glMultiTexCoord3fvARB		;
		PFNGLMULTITEXCOORD3IARBPROC 				glMultiTexCoord3iARB 		;
		PFNGLMULTITEXCOORD3IVARBPROC				glMultiTexCoord3ivARB		;
		PFNGLMULTITEXCOORD3SARBPROC 				glMultiTexCoord3sARB 		;
		PFNGLMULTITEXCOORD3SVARBPROC				glMultiTexCoord3svARB		;
		PFNGLMULTITEXCOORD4DARBPROC 				glMultiTexCoord4dARB 		;
		PFNGLMULTITEXCOORD4DVARBPROC				glMultiTexCoord4dvARB		;
		PFNGLMULTITEXCOORD4FARBPROC 				glMultiTexCoord4fARB 		;
		PFNGLMULTITEXCOORD4FVARBPROC				glMultiTexCoord4fvARB		;
		PFNGLMULTITEXCOORD4IARBPROC 				glMultiTexCoord4iARB 		;
		PFNGLMULTITEXCOORD4IVARBPROC				glMultiTexCoord4ivARB		;
		PFNGLMULTITEXCOORD4SARBPROC 				glMultiTexCoord4sARB 		;
		PFNGLMULTITEXCOORD4SVARBPROC				glMultiTexCoord4svARB		;

		PROC		GetProcAddr(const char *str);
		void		Init(void);
	};